"""Comprehensive unit tests for the Canvas LMS REST API client."""

from __future__ import annotations

import asyncio
from urllib.parse import parse_qs
from unittest.mock import AsyncMock, patch

import aiohttp
import pytest

from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from pytest_homeassistant_custom_component.test_util.aiohttp import AiohttpClientMocker

from custom_components.canvas.api import (
    CanvasApiClient,
    _parse_next_link,
)
from custom_components.canvas.const import (
    API_TIMEOUT,
    COURSE_INCLUDES,
    COURSE_STATES,
    DEFAULT_ACCEPT_TYPE,
    DEFAULT_PAGE_SIZE,
    DEFAULT_USER_AGENT,
    ENDPOINT_COURSE_STUDENT_SUBMISSIONS,
    ENDPOINT_USER_COURSES,
    ENDPOINT_USERS_OBSERVEES,
    ENDPOINT_USERS_SELF,
    HEADER_ACCEPT,
    HEADER_AUTHORIZATION,
    HEADER_LINK,
    HEADER_RATE_LIMIT_REMAINING,
    HEADER_USER_AGENT,
    SUBMISSION_INCLUDES,
)
from custom_components.canvas.exceptions import (
    CanvasAuthError,
    CanvasConnectionError,
    CanvasError,
    CanvasRateLimitError,
    CanvasResponseError,
)
from custom_components.canvas.models import (
    CanvasAssignment,
    CanvasCourse,
    CanvasObservee,
    CanvasSubmission,
    CanvasUser,
)

from .conftest import (
    MOCK_COURSES_RESPONSE,
    MOCK_OBSERVEES_RESPONSE,
    MOCK_SUBMISSIONS_RESPONSE,
    MOCK_USER_SELF_RESPONSE,
    TEST_ACCESS_TOKEN,
    TEST_BASE_URL,
    TEST_USER_ID,
    build_link_header,
)


# ============================================================================
# Section 1: Client Initialization, URL Normalization & Headers
# ============================================================================


class TestCanvasApiClientInit:
    """Test suite for CanvasApiClient initialization and header preparation."""

    def test_init_url_normalization(self) -> None:
        """Test base URL normalization: trailing slash stripping and scheme inference."""
        session = AsyncMock(spec=aiohttp.ClientSession)

        # Standard HTTPS URL with trailing slash
        client1 = CanvasApiClient(
            "https://canvas.example.edu/", TEST_ACCESS_TOKEN, session
        )
        assert client1.base_url == "https://canvas.example.edu"
        assert client1.access_token == TEST_ACCESS_TOKEN

        # URL with whitespace
        client2 = CanvasApiClient(
            "  https://canvas.example.edu/  ", f"  {TEST_ACCESS_TOKEN}  ", session
        )
        assert client2.base_url == "https://canvas.example.edu"
        assert client2.access_token == TEST_ACCESS_TOKEN

        # URL without scheme defaults to https
        client3 = CanvasApiClient("canvas.example.edu", TEST_ACCESS_TOKEN, session)
        assert client3.base_url == "https://canvas.example.edu"

        # HTTP scheme is preserved
        client4 = CanvasApiClient(
            "http://canvas.local:8080/", TEST_ACCESS_TOKEN, session
        )
        assert client4.base_url == "http://canvas.local:8080"

    def test_init_headers_and_defaults(self) -> None:
        """Test standard headers generated by the client."""
        session = AsyncMock(spec=aiohttp.ClientSession)
        client = CanvasApiClient(
            TEST_BASE_URL,
            TEST_ACCESS_TOKEN,
            session,
            timeout=30,
        )

        headers = client._headers
        assert headers[HEADER_AUTHORIZATION] == f"Bearer {TEST_ACCESS_TOKEN}"
        assert headers[HEADER_ACCEPT] == DEFAULT_ACCEPT_TYPE
        assert headers[HEADER_USER_AGENT] == DEFAULT_USER_AGENT
        assert client._timeout == 30
        assert client.rate_limit_remaining is None

    def test_init_default_timeout(self) -> None:
        """Test default timeout assignment."""
        session = AsyncMock(spec=aiohttp.ClientSession)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)
        assert client._timeout == API_TIMEOUT


# ============================================================================
# Section 2: RFC 5988 Link Header Parsing
# ============================================================================


class TestLinkHeaderParsing:
    """Test suite for RFC 5988 Link header extraction."""

    @pytest.mark.parametrize(
        ("link_header", "expected_next_url"),
        [
            # Single next link with double quotes
            (
                '<https://canvas.example.edu/api/v1/courses?page=2&per_page=100>; rel="next"',
                "https://canvas.example.edu/api/v1/courses?page=2&per_page=100",
            ),
            # Single next link with single quotes
            (
                "<https://canvas.example.edu/api/v1/courses?page=2>; rel='next'",
                "https://canvas.example.edu/api/v1/courses?page=2",
            ),
            # Single next link without quotes
            (
                "<https://canvas.example.edu/api/v1/courses?page=2>; rel=next",
                "https://canvas.example.edu/api/v1/courses?page=2",
            ),
            # Multiple relations (current, next, first, last)
            (
                '<https://canvas.example.edu/api/v1/courses?page=1>; rel="current", '
                '<https://canvas.example.edu/api/v1/courses?page=2>; rel="next", '
                '<https://canvas.example.edu/api/v1/courses?page=1>; rel="first", '
                '<https://canvas.example.edu/api/v1/courses?page=5>; rel="last"',
                "https://canvas.example.edu/api/v1/courses?page=2",
            ),
            # Extra spaces around relation
            (
                '<https://canvas.example.edu/api/v1/courses?page=3> ;  rel = "next" ; title="Next Page"',
                "https://canvas.example.edu/api/v1/courses?page=3",
            ),
            # Terminal page (no rel="next")
            (
                '<https://canvas.example.edu/api/v1/courses?page=5>; rel="current", '
                '<https://canvas.example.edu/api/v1/courses?page=4>; rel="prev", '
                '<https://canvas.example.edu/api/v1/courses?page=1>; rel="first"',
                None,
            ),
            # Empty and None header
            ("", None),
            (None, None),
            # Malformed link headers
            ("not-a-valid-link-header", None),
            ("https://canvas.example.edu/courses; rel=next", None),
            ("<>; rel=next", ""),
        ],
    )
    def test_parse_next_link(
        self, link_header: str | None, expected_next_url: str | None
    ) -> None:
        """Test _parse_next_link correctly extracts next page URLs or returns None."""
        assert _parse_next_link(link_header) == expected_next_url


# ============================================================================
# Section 3: Tier 1 Core Endpoints & Data Retrieval
# ============================================================================


class TestCoreEndpoints:
    """Tier 1: Feature tests for core Canvas LMS API endpoints."""

    async def test_async_get_current_user_success(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test successful retrieval and parsing of current user profile."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json=MOCK_USER_SELF_RESPONSE,
            headers={HEADER_RATE_LIMIT_REMAINING: "600.0"},
        )

        user = await client.async_get_current_user()
        assert isinstance(user, CanvasUser)
        assert user.id == TEST_USER_ID
        assert user.name == "Allen Porter"
        assert user.sortable_name == "Porter, Allen"
        assert user.short_name == "Allen"
        assert user.primary_email == "allen@example.edu"
        assert client.rate_limit_remaining == 600.0

    async def test_async_get_current_user_non_dict_raises(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test async_get_current_user raises CanvasResponseError when receiving non-dict."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json=["not", "a", "dict"],
        )

        with pytest.raises(CanvasResponseError, match="Expected user profile object"):
            await client.async_get_current_user()

    async def test_async_get_current_user_malformed_dict_raises(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test async_get_current_user raises CanvasResponseError when dict is missing required id."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json={"name": "No ID User"},
        )

        with pytest.raises(CanvasResponseError, match="Malformed user profile object"):
            await client.async_get_current_user()

    async def test_async_get_observees_success(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test retrieval and parsing of linked observees."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_OBSERVEES}",
            json=MOCK_OBSERVEES_RESPONSE,
        )

        observees = await client.async_get_observees()
        assert len(observees) == 2
        assert isinstance(observees[0], CanvasObservee)
        assert observees[0].id == 6021
        assert observees[0].name == "Quentin Porter"
        assert observees[0].pronouns == "He/Him"
        assert observees[0].root_account_ids == (1,)
        assert observees[1].id == 4899
        assert observees[1].name == "Theodore Porter"

    async def test_async_get_observees_empty(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test async_get_observees returns empty list when user has no linked students."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_OBSERVEES}",
            json=[],
        )

        observees = await client.async_get_observees()
        assert observees == []

    async def test_async_get_student_courses_success_and_query_params(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test retrieval of student courses with verified query parameters."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        student_id = 6021
        endpoint = ENDPOINT_USER_COURSES.format(user_id=student_id)
        url = f"{TEST_BASE_URL}{endpoint}"

        aioclient_mock.get(
            url,
            json=MOCK_COURSES_RESPONSE,
        )

        courses = await client.async_get_student_courses(student_id)
        assert len(courses) == 1
        assert isinstance(courses[0], CanvasCourse)
        assert courses[0].id == 7349
        assert courses[0].name == "AP US History"
        assert courses[0].term is not None
        assert courses[0].term.name == "Fall 2026"
        assert len(courses[0].teachers) == 1
        assert courses[0].teachers[0].display_name == "Dr. Jon Asoulin"
        assert courses[0].primary_grade is not None
        assert courses[0].primary_grade.current_score == 92.5
        assert courses[0].primary_grade.current_grade == "A-"

        # Verify request parameters
        assert len(aioclient_mock.mock_calls) == 1
        req_url = aioclient_mock.mock_calls[0][1]
        parsed_params = parse_qs(req_url.query_string)
        assert parsed_params.get("per_page") == [str(DEFAULT_PAGE_SIZE)]
        assert set(parsed_params.get("include[]", [])) == set(COURSE_INCLUDES)
        assert set(parsed_params.get("state[]", [])) == set(COURSE_STATES)

    async def test_async_get_student_submissions_success_and_query_params(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test retrieval of student submissions with verified query parameters."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        course_id = 7349
        student_id = 6021
        endpoint = ENDPOINT_COURSE_STUDENT_SUBMISSIONS.format(course_id=course_id)
        url = f"{TEST_BASE_URL}{endpoint}"

        aioclient_mock.get(
            url,
            json=MOCK_SUBMISSIONS_RESPONSE,
        )

        submissions = await client.async_get_student_submissions(course_id, student_id)
        assert len(submissions) == 1
        assert isinstance(submissions[0], CanvasSubmission)
        assert submissions[0].id == 5196766
        assert submissions[0].assignment_id == 134664
        assert submissions[0].user_id == 6021
        assert submissions[0].workflow_state == "unsubmitted"

        # Verify request parameters
        assert len(aioclient_mock.mock_calls) == 1
        req_url = aioclient_mock.mock_calls[0][1]
        parsed_params = parse_qs(req_url.query_string)
        assert parsed_params.get("per_page") == [str(DEFAULT_PAGE_SIZE)]
        assert parsed_params.get("student_ids[]") == [str(student_id)]
        assert set(parsed_params.get("include[]", [])) == set(SUBMISSION_INCLUDES)

    async def test_async_get_student_assignments_success(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test retrieval of assignments with embedded student submissions."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        course_id = 7349
        student_id = 6021
        endpoint = ENDPOINT_COURSE_STUDENT_SUBMISSIONS.format(course_id=course_id)
        url = f"{TEST_BASE_URL}{endpoint}"

        aioclient_mock.get(
            url,
            json=MOCK_SUBMISSIONS_RESPONSE,
        )

        assignments = await client.async_get_student_assignments(course_id, student_id)
        assert len(assignments) == 1
        assert isinstance(assignments[0], CanvasAssignment)
        assert assignments[0].id == 134664
        assert assignments[0].course_id == 7349
        assert assignments[0].name == "Chapter 1 Reflection"
        assert assignments[0].submission is not None
        assert assignments[0].submission.id == 5196766
        assert assignments[0].submission.workflow_state == "unsubmitted"

    async def test_async_get_student_submissions_edge_cases(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test student submissions handling of non-dict and invalid items."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        course_id = 7349
        student_id = 6021
        endpoint = ENDPOINT_COURSE_STUDENT_SUBMISSIONS.format(course_id=course_id)
        url = f"{TEST_BASE_URL}{endpoint}"

        aioclient_mock.get(
            url,
            json=[
                {"id": 1, "assignment_id": 10, "user_id": 20},
                "not-a-dict",
                {},
            ],
        )

        submissions = await client.async_get_student_submissions(course_id, student_id)
        assert len(submissions) == 1
        assert submissions[0].id == 1

    async def test_async_get_student_assignments_edge_cases(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test student assignments handling of non-dict items and missing assignment attributes."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        course_id = 7349
        student_id = 6021
        endpoint = ENDPOINT_COURSE_STUDENT_SUBMISSIONS.format(course_id=course_id)
        url = f"{TEST_BASE_URL}{endpoint}"

        aioclient_mock.get(
            url,
            json=[
                {
                    "id": 1,
                    "assignment_id": 10,
                    "user_id": 20,
                    "assignment": {"id": 10, "course_id": course_id, "name": "A1"},
                },
                "not-a-dict",
                {"id": 2, "user_id": 20},
                {"id": 3, "assignment": "not-a-dict"},
                {"id": 4, "assignment": {"name": "No ID"}},
            ],
        )

        assignments = await client.async_get_student_assignments(course_id, student_id)
        assert len(assignments) == 1
        assert assignments[0].id == 10
        assert assignments[0].name == "A1"


# ============================================================================
# Section 4: RFC 5988 Pagination Traversal & Edge Cases
# ============================================================================


class TestPaginationTraversal:
    """Test suite for paginated collection requests using RFC 5988 Link headers."""

    async def test_multi_page_pagination_traversal(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test multi-page pagination traversing rel='next' links across pages."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        page1_url = f"{TEST_BASE_URL}{ENDPOINT_USERS_OBSERVEES}"
        page2_url = f"{TEST_BASE_URL}/api/v1/users/self/observees?page=2&per_page=100"

        page1_data = [{"id": 1, "name": "Student One"}]
        page2_data = [{"id": 2, "name": "Student Two"}]

        link_header_page1 = build_link_header(
            current_url=page1_url,
            next_url=page2_url,
            first_url=page1_url,
            last_url=page2_url,
        )

        # Register page 2 first (more specific URL) so AiohttpClientMocker prioritizes it
        aioclient_mock.get(
            page2_url,
            json=page2_data,
            headers={},  # Terminal page without Link header
        )
        aioclient_mock.get(
            page1_url,
            json=page1_data,
            headers={HEADER_LINK: link_header_page1},
        )

        observees = await client.async_get_observees()
        assert len(observees) == 2
        assert observees[0].id == 1
        assert observees[0].name == "Student One"
        assert observees[1].id == 2
        assert observees[1].name == "Student Two"
        assert len(aioclient_mock.mock_calls) == 2

    async def test_pagination_stops_on_empty_page(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test pagination halts when an empty list payload is encountered."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        page1_url = f"{TEST_BASE_URL}{ENDPOINT_USERS_OBSERVEES}"
        aioclient_mock.get(
            page1_url,
            json=[],
            headers={
                HEADER_LINK: f'<{TEST_BASE_URL}/api/v1/users/self/observees?page=2>; rel="next"'
            },
        )

        observees = await client.async_get_observees()
        assert observees == []
        # Halts immediately on empty payload without fetching page 2
        assert len(aioclient_mock.mock_calls) == 1

    async def test_pagination_circular_reference_safeguard(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test circular pagination detection prevents infinite loops."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        page1_url = f"{TEST_BASE_URL}{ENDPOINT_USERS_OBSERVEES}"
        page2_url = f"{TEST_BASE_URL}/api/v1/users/self/observees?page=2"

        # Page 1 links to Page 2; Page 2 maliciously links back to Page 1
        aioclient_mock.get(
            page2_url,
            json=[{"id": 2, "name": "Student 2"}],
            headers={HEADER_LINK: f'<{page1_url}>; rel="next"'},
        )
        aioclient_mock.get(
            page1_url,
            json=[{"id": 1, "name": "Student 1"}],
            headers={HEADER_LINK: f'<{page2_url}>; rel="next"'},
        )

        observees = await client.async_get_observees()
        assert len(observees) == 2
        assert observees[0].id == 1
        assert observees[1].id == 2
        # Safely stops after detecting page1 was already visited
        assert len(aioclient_mock.mock_calls) == 2

    async def test_pagination_max_pages_limit(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test max_pages boundary limits excessive page requests."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        endpoint = "/api/v1/courses"
        url1 = f"{TEST_BASE_URL}{endpoint}"
        url2 = f"{TEST_BASE_URL}{endpoint}?page=2"
        url3 = f"{TEST_BASE_URL}{endpoint}?page=3"

        aioclient_mock.get(
            url3,
            json=[{"id": 3}],
            headers={},
        )
        aioclient_mock.get(
            url2,
            json=[{"id": 2}],
            headers={HEADER_LINK: f'<{url3}>; rel="next"'},
        )
        aioclient_mock.get(
            url1,
            json=[{"id": 1}],
            headers={HEADER_LINK: f'<{url2}>; rel="next"'},
        )

        items = await client._request_paginated(endpoint, max_pages=2)
        assert len(items) == 2
        assert items[0]["id"] == 1
        assert items[1]["id"] == 2
        assert len(aioclient_mock.mock_calls) == 2

    async def test_pagination_non_list_payload_safeguard(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test pagination terminates cleanly if an unexpected non-list payload is returned."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        endpoint = "/api/v1/users/self/observees"
        aioclient_mock.get(
            f"{TEST_BASE_URL}{endpoint}",
            json={"error": "unexpected object instead of array"},
        )

        items = await client._request_paginated(endpoint)
        assert items == []


# ============================================================================
# Section 5: Rate Limiting & Header Tracking
# ============================================================================


class TestRateLimiting:
    """Test suite for Canvas LMS API rate limit header parsing and quota handling."""

    async def test_rate_limit_header_parsed_and_low_warning(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test X-Rate-Limit-Remaining updates client property and logs warning when low."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json=MOCK_USER_SELF_RESPONSE,
            headers={HEADER_RATE_LIMIT_REMAINING: "25.5"},
        )

        with patch("custom_components.canvas.api._LOGGER.warning") as mock_warn:
            user = await client.async_get_current_user()
            assert user.id == TEST_USER_ID
            assert client.rate_limit_remaining == 25.5
            mock_warn.assert_called_once()
            assert (
                "Canvas API rate limit remaining is low: 25.5"
                in mock_warn.call_args[0][0] % mock_warn.call_args[0][1]
            )

    async def test_rate_limit_header_zero_raises_rate_limit_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test X-Rate-Limit-Remaining <= 0 raises CanvasRateLimitError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json=MOCK_USER_SELF_RESPONSE,
            headers={HEADER_RATE_LIMIT_REMAINING: "0.0"},
        )

        with pytest.raises(CanvasRateLimitError, match="rate limit quota exhausted"):
            await client.async_get_current_user()

    async def test_rate_limit_malformed_header_ignored_safely(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test non-numeric X-Rate-Limit-Remaining is safely ignored."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            json=MOCK_USER_SELF_RESPONSE,
            headers={HEADER_RATE_LIMIT_REMAINING: "not-a-number"},
        )

        user = await client.async_get_current_user()
        assert user.id == TEST_USER_ID
        assert client.rate_limit_remaining is None

    async def test_http_429_raises_rate_limit_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test HTTP 429 status code raises CanvasRateLimitError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=429,
            text="429 Too Many Requests: Rate limit exceeded",
        )

        with pytest.raises(
            CanvasRateLimitError, match="Canvas API rate limit exceeded"
        ):
            await client.async_get_current_user()

    async def test_http_403_rate_limit_exceeded_body_raises_rate_limit_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test HTTP 403 with Rate Limit Exceeded body raises CanvasRateLimitError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=403,
            text="Rate Limit Exceeded: slow down",
        )

        with pytest.raises(
            CanvasRateLimitError, match="Canvas API rate limit exceeded"
        ):
            await client.async_get_current_user()


# ============================================================================
# Section 6: Tier 2 Exception Mapping & Boundary Edge Cases
# ============================================================================


class TestExceptionMappingAndEdgeCases:
    """Tier 2: Comprehensive exception translation and network failure tests."""

    @pytest.mark.parametrize(
        ("status_code", "body_text", "expected_exception"),
        [
            (401, "Invalid access token", CanvasAuthError),
            (403, "User not authorized to access endpoint", CanvasAuthError),
        ],
    )
    async def test_http_auth_errors_raise_canvas_auth_error(
        self,
        hass: HomeAssistant,
        aioclient_mock: AiohttpClientMocker,
        status_code: int,
        body_text: str,
        expected_exception: type[Exception],
    ) -> None:
        """Test HTTP 401 and 403 raise CanvasAuthError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=status_code,
            text=body_text,
        )

        with pytest.raises(expected_exception) as exc_info:
            await client.async_get_current_user()
        assert f"HTTP {status_code}" in str(exc_info.value)
        assert body_text in str(exc_info.value)

    @pytest.mark.parametrize(
        "status_code",
        [500, 502, 503, 504],
    )
    async def test_http_server_errors_raise_canvas_connection_error(
        self,
        hass: HomeAssistant,
        aioclient_mock: AiohttpClientMocker,
        status_code: int,
    ) -> None:
        """Test HTTP 5xx errors raise CanvasConnectionError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=status_code,
            text=f"Server error {status_code}",
        )

        with pytest.raises(CanvasConnectionError, match=f"HTTP {status_code}"):
            await client.async_get_current_user()

    @pytest.mark.parametrize(
        "status_code",
        [400, 404, 422],
    )
    async def test_http_client_errors_raise_canvas_response_error(
        self,
        hass: HomeAssistant,
        aioclient_mock: AiohttpClientMocker,
        status_code: int,
    ) -> None:
        """Test HTTP 4xx (non-auth, non-429) errors raise CanvasResponseError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=status_code,
            text=f"Client error {status_code}",
        )

        with pytest.raises(CanvasResponseError, match=f"HTTP {status_code}"):
            await client.async_get_current_user()

    async def test_invalid_json_response_raises_canvas_response_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test invalid or unparsable JSON payload raises CanvasResponseError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            status=200,
            text="<html><body>502 Bad Gateway Nginx</body></html>",
            headers={"Content-Type": "text/html"},
        )

        with pytest.raises(
            CanvasResponseError, match="Invalid JSON received from Canvas"
        ):
            await client.async_get_current_user()

    async def test_timeout_raises_canvas_connection_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test request timeout raises CanvasConnectionError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            exc=asyncio.TimeoutError("Connection timed out"),
        )

        with pytest.raises(
            CanvasConnectionError, match="Timeout connecting to Canvas LMS"
        ):
            await client.async_get_current_user()

    async def test_client_connector_error_raises_canvas_connection_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test aiohttp ClientConnectorError raises CanvasConnectionError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            exc=aiohttp.ClientConnectorError(
                connection_key=AsyncMock(),
                os_error=OSError(111, "Connection refused"),
            ),
        )

        with pytest.raises(
            CanvasConnectionError, match="Network error connecting to Canvas LMS"
        ):
            await client.async_get_current_user()

    async def test_generic_unexpected_exception_raises_canvas_error(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test unexpected generic Exception is wrapped in CanvasError."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        aioclient_mock.get(
            f"{TEST_BASE_URL}{ENDPOINT_USERS_SELF}",
            exc=RuntimeError("Catastrophic hardware fault"),
        )

        with pytest.raises(
            CanvasError, match="Unexpected error during Canvas API request"
        ):
            await client.async_get_current_user()

    async def test_absolute_url_direct_request(
        self, hass: HomeAssistant, aioclient_mock: AiohttpClientMocker
    ) -> None:
        """Test _async_request handles absolute URLs directly without prefixing base_url."""
        session = async_get_clientsession(hass)
        client = CanvasApiClient(TEST_BASE_URL, TEST_ACCESS_TOKEN, session)

        external_url = "https://custom-canvas-cluster.example.edu/api/v1/users/self"
        aioclient_mock.get(
            external_url,
            json=MOCK_USER_SELF_RESPONSE,
        )

        payload, _ = await client._async_request("GET", external_url)
        assert payload["id"] == TEST_USER_ID
        assert len(aioclient_mock.mock_calls) == 1
        assert str(aioclient_mock.mock_calls[0][1]) == external_url
